# Setup
title:               Renowacje pokojowe
tagline:             'Pracownia renowacji antyków w sercu Krakowa'
description:         ''
url:                 https://renowacjepokojowe.pl
baseurl:             ''
paginate:            3
permalink:           pretty

# About/contact
author:
  name:              Lech Peres
  url:               https://renowacjepokojowe.pl
  email:             kontakt@renowacjepokojowe.pl

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
